# Recursive Hamming Code

**Mahan Madani - 99222092**

In [36]:
import numpy as np
import sympy as sp
import pprint

### Hamming Code Generator Matrix

In [68]:
def generate_codewords(generator_matrix):   # Generate all possible codewords from the generator matrix
    codewords = []
    k, n = generator_matrix.shape

    for i in range(2**k):
        message = np.array(list(map(int, bin(i)[2:].zfill(k))))          # generate all binary message from 0 to 2^k
        codeword = np.dot(message, generator_matrix) % 2                 # find the encoded value of each binary message
        codewords.append(codeword)
        
    return np.array(codewords)

In [69]:
G1 = np.array([[1]])

def hamming_generator(r):   # hamming generator - calculated recursively
    if r == 1:
        return G1
    
    G_r_1 = hamming_generator(r-1)
    m, n = G_r_1.shape

    G_r = np.zeros([m+1, 2*n+1], dtype=int)

    G_r[1:m+1, :n] = G_r_1
    G_r[1:m+1, n+1:] = G_r_1
    G_r[0, n:] = np.ones(n+1)

    return G_r

In [70]:
print(hamming_generator(3))

[[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]]


In [79]:
print(hamming_generator(4))

[[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [81]:
print(hamming_generator(5))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [71]:
generate_codewords(hamming_generator(3))

array([[0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 1]], dtype=int32)

In [82]:
generate_codewords(hamming_generator(4))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0]], dtype=int32)